site_name: Kubernetes Observability Recipes
site_description: 'A collection of Kubernetes observability recipes and tips & tricks'
site_author: 'Torsten Bøgh Köster'
repo_name: 'o12stack/recipes'
repo_url: 'https://github.com/observabilitystack/recipes'
#copyright: ''
nav:
    - Recipes: index.md
    - Log Management: log-management/index.md
    - Monitoring: monitoring/index.md
    #- Testing: testing.md
    - Kubernetes Tools: tools.md
theme:
    name: 'material'
    palette:
      primary: 'blue'
      accent: 'amber'
    highlightjs: true
    hljs_languages:
        - yaml
        - json
        - bash
extra:
  social:
    - type: 'github'
      link: 'https://github.com/tboeghk'
    - type: 'twitter'
      link: 'https://twitter.com/tboeghk'
    - type: 'wordpress'
      link: 'https://www.thiswayup.de'
plugins: []
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite:
        linenums: true